quarkus:
  http:
    test-port: 8081
  
  datasource:
    db-kind: h2
    jdbc:
      url: "jdbc:h2:mem:notification-test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password: 
  
  hibernate-orm:
    database:
      generation: drop-and-create
    packages:
      scan: "com.apporte.core.model"
    sql-load-script: no-file
  
  oidc:
    enabled: false
  
  security:
    auth:
      basic: true
      permission:
        default: permit-all
  
  mailer:
    mock: true
  
  log:
    level: WARN
    console:
      enable: true
  
  swagger-ui:
    always-include: false

app:
  environment: "test"
  base-url: "http://localhost:8081"
  
  notification:
    retry:
      max-attempts: 1
    whatsapp:
      enabled: false
      mock: true
    email:
      mock: true
  
  features:
    mock-mode: true